name: Publish DB to AWS RDS
env:
  DOTNET_VERSION: '6.x'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'soccer/MatchResultDb/**'
      - '.github/workflows/RDS_Publish.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-db:
    runs-on: windows-latest

    steps:        
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # - name: Copy files
      #   run: |
      #     $destinationDir = "C:/Users/runneradmin/AppData/Local/Microsoft/dotnet/sdk/6.0.415/Microsoft/VisualStudio/v11.0/SSDT/"
      #     $sourceDir = "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Microsoft/VisualStudio/v17.0/SSDT/"
      #     New-Item -Path $destinationDir -ItemType Directory -Force
      #     Copy-Item -Path $sourceDir\* -Destination $destinationDir -Recurse

      #     $sourceDir = "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/Extensions/Microsoft/SQLDB/DAC/"
      #     $destinationDir = "D:\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\"
      #     New-Item -Path $destinationDir -ItemType Directory -Force
      #     Copy-Item -Path $sourceDir\* -Destination $destinationDir -Recurse

      #     cd "D:\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\"
      #     Get-ChildItem

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        
      - name: Build SQL Server Database Project
        run: msbuild ./soccer/MatchResultDb -t:build -property:Configuration=Release

      - name: list files
        run : |
          cd "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/Extensions/Microsoft/SQLDB/DAC/"       
          Get-ChildItem
          cd "D:\a\SoccerProject\SoccerProject\soccer\MatchResultDb\bin\Release\"
          Get-ChildItem
          
      # - name: Add sqlpackage to PATH
      #   uses: coreywebber/setup-sqlpackage@v1
      #   with:
      #     sql-version: 17
  
      - name: Deploy to AWS RDS
        env:
          AWS_REGION: ap-southeast-1
          RDS_ENDPOINT: ${{ secrets.RDS_SERVER }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          USERNAME: ${{ secrets.RDS_USERNAME }}
          PASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: |
          "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/Extensions/Microsoft/SQLDB/DAC/SqlPackage.exe" /Action:Publish /SourceFile:"D:\a\SoccerProject\SoccerProject\soccer\MatchResultDb\bin\Release\MatchResultDb.dacpac" /TargetServer:$RDS_ENDPOINT /TargetDatabase:$DATABASE_NAME /TargetUser:$USERNAME /TargetPassword:$PASSWORD /p:BlockOnPossibleDataLoss=false
