name: Publish DB to AWS RDS
env:
  DOTNET_VERSION: '6.x'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'soccer/MatchResultDb/**'
      - '.github/workflows/RDS_Publish.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-db:
    runs-on: windows-latest

    steps:        
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install SQL Server Data Tools (SSDT)
        run: |
          choco install ssdt17

      - name: List files
        run: |
          cd C:/Users/runneradmin/AppData/Local/Microsoft/dotnet/
          Get-ChildItem
          
      - name: Restore dependencies
        run: dotnet restore ./soccer/MatchResultDb

      - name: Build SQL Server Database Project
        run: dotnet publish ./soccer/MatchResultDb -o ./build-artifacts
        
      - name: Publish Database to RDS
        run: |
          export RDS_SERVER = ${{ secrets.RDS_SERVER }}
          export RDS_USERNAME = ${{ secrets.RDS_USERNAME }}
          export RDS_PASSWORD = ${{ secrets.RDS_PASSWORD }}
          export RDS_PORT = 1433
          export DATABASE_NAME = ${{ secrets.DATABASE_NAME }}

          sqlpackage /a:Publish /tsn:$RDS_SERVER /tdn:$DATABASE_NAME /tu:$RDS_USERNAME /tp:$RDS_PASSWORD /tcp:$RDS_PORT /sf:./build-artifacts/MatchResultDb.dacpac
